# Generated by Django 4.0.2 on 2022-02-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rollno',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
