# Generated by Django 4.0.2 on 2022-02-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_rollno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rollno',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
