# Generated by Django 4.0.2 on 2022-03-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_rollno'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='status',
            field=models.CharField(choices=[('on_campus', 'On Campus'), ('off_Campus', 'Off Campus')], default='on_campus', max_length=20),
        ),
    ]
