# Generated by Django 4.0.2 on 2022-03-08 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_myuser_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='status',
            new_name='campus_status',
        ),
    ]
