# Generated by Django 4.0.2 on 2022-03-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_status_myuser_campus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='campus_status',
            field=models.CharField(choices=[('on_campus', 'On Campus'), ('off_campus', 'Off Campus')], default='on_campus', max_length=20),
        ),
    ]
