# Generated by Django 4.0.2 on 2022-04-26 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userroles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userroles',
            options={'verbose_name': 'User Roles', 'verbose_name_plural': 'User Roles'},
        ),
        migrations.AddField(
            model_name='myuser',
            name='my_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='r_users', to='users.userroles'),
        ),
    ]
