# Generated by Django 4.0.2 on 2022-02-28 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('hostel', 'number')},
        ),
    ]
