# Generated by Django 4.0.2 on 2022-03-01 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_alter_room_options_requestchangeroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestchangeroom',
            name='room_preferences',
            field=models.ManyToManyField(blank=True, related_name='room_preferences', to='rooms.Room'),
        ),
    ]
