# Generated by Django 4.0.2 on 2022-03-01 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_alter_requestchangeroom_room_preferences'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestchangeroom',
            old_name='room_preferences',
            new_name='preferences',
        ),
    ]
