# Generated by Django 4.0.2 on 2022-03-01 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_rename_room_preferences_requestchangeroom_preferences'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestChangeRoom',
        ),
    ]
