# Generated by Django 4.0.2 on 2022-03-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_requestchangeroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestchangeroom',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved')], default='pending', max_length=20),
        ),
    ]
