# Generated by Django 4.0.2 on 2022-04-26 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_userroles_options_myuser_my_role'),
        ('rooms', '0011_hostel_warden'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='representative',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rep_hostel', to='users.profile'),
        ),
    ]
