# Generated by Django 4.0.2 on 2022-04-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0002_alter_fooditem_days_alter_fooditem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
