# Generated by Django 4.0.2 on 2022-03-08 19:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0002_visitorrecords_alter_leaveapplication_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentstaffinoutrecords',
            options={'verbose_name': 'Student Staff InOut Records', 'verbose_name_plural': 'Student Staff InOut Records'},
        ),
        migrations.AlterModelOptions(
            name='visitorrecords',
            options={'verbose_name': 'Visitor Records', 'verbose_name_plural': 'Visitor Records'},
        ),
        migrations.AddField(
            model_name='visitorrecords',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{10}$')]),
        ),
    ]
