# Generated by Django 4.0.2 on 2022-04-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0003_alter_studentstaffinoutrecords_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentstaffinoutrecords',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
