# Generated by Django 4.0.2 on 2022-04-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0004_studentstaffinoutrecords_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentstaffinoutrecords',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('done', 'Done')], default='draft', max_length=20),
        ),
    ]
