# Generated by Django 4.0.2 on 2022-04-05 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0005_studentstaffinoutrecords_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentstaffinoutrecords',
            name='request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='in_out_record', to='leave_management.leaveapplication'),
        ),
    ]
