# Generated by Django 4.0.2 on 2022-05-08 10:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0007_historicalstudentstaffinoutrecords'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='contact_no',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{10}$')]),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='destination',
            field=models.TextField(default='Raichur'),
            preserve_default=False,
        ),
    ]
