# Generated by Django 4.0.2 on 2022-03-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
