# Generated by Django 3.2.1 on 2022-03-06 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_remarks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['status'], 'verbose_name': 'Complaint', 'verbose_name_plural': 'Complaints'},
        ),
    ]
