# Generated by Django 4.0.2 on 2022-03-06 06:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_complaint_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['status', '-created_at'], 'verbose_name': 'Complaint', 'verbose_name_plural': 'Complaints'},
        ),
        migrations.AlterField(
            model_name='complaint',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
