# Generated by Django 4.0.2 on 2022-03-06 06:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_alter_complaint_options_alter_complaint_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
